[package]
name = "fast-readline"
version = "0.1.0"
authors = ["st1page <1245835950@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libaio-futures = { path = "../libaio-futures" }
